### PR TITLE
Deployed app to Heroku

### PR DESCRIPTION
**Pull request by euqueme**
In this branch we deployed the application to Heroku and also, added the authentication with omniauth, and fix some extra behavior, we also updated the Readme file using the best readme template

Thank you for your review.

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required

Hello, nice deployment.
However, it seems like there is a problem with `Sign up with Facebook`
Screenshot_2020-02-28_22-57-46

> Error
Application not configured: This application is currently under development, and you cannot access it. Use an authorized test user account or contact an application administrator for access rights.

Also, there is that error
Screenshot_2020-02-28_23-03-17

Kindly fix those errors and submit a new code review request.
Mael FOSSO

**Comment by euqueme** [comment]
> # Changes required
> Hello, nice deployment.
> However, it seems like there is a problem with `Sign up with Facebook`
> Screenshot_2020-02-28_22-57-46
> 
> > Error
> > Application not configured: This application is currently under development, and you cannot access it. Use an authorized test user account or contact an application administrator for access rights.
> 
> Also, there is that error
> Screenshot_2020-02-28_23-03-17
> 
> Kindly fix those errors and submit a new code review request.
> Mael FOSSO

Hello @maelfosso :wave: 

we corrected with the right configuration now it should work properly

**Comment by euqueme** [comment]
The pull request automatically merged and closed when submitted to master for deployment

**Comment by samgaco** [comment]
Everything working. The project is approved :+1: 

------------------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

**Pull request merged**
